#date 11.30f
#v1 liyue
server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5

spring:
  application:
    name: owinfo-common-zuul


  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


zuul:
  sensitive-headers: true
  routes:
    demo:
      path: /owinfoProject/**
      serviceId: owinfo-project-web
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

  eureka:
    enabled: true


#logging:
#  file: ../../logs/zuul_log.log
#  level:
#    org.springfromework.web: debug