
package com.owinfo.web.webservice.org.tempuri;

import com.owinfo.web.webservice.org.datacontract.schemas._2004._07.owinfo_message.ArrayOfTaskOperationMessage;
import com.owinfo.web.webservice.org.datacontract.schemas._2004._07.owinfo_message.TaskOperationResult;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMessageCenterService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
        com.owinfo.web.webservice.com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
        com.owinfo.web.webservice.org.datacontract.schemas._2004._07.owinfo_message.ObjectFactory.class,
        com.owinfo.web.webservice.org.tempuri.ObjectFactory.class
})
public interface IMessageCenterService {


    /**
     * 
     * @param tasks
     * @return
     *     returns org.datacontract.schemas._2004._07.owinfo_message.TaskOperationResult
     */
    @WebMethod(operationName = "MixOperateTasks", action = "http://tempuri.org/IMessageCenterService/MixOperateTasks")
    @WebResult(name = "MixOperateTasksResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MixOperateTasks", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MixOperateTasks")
    @ResponseWrapper(localName = "MixOperateTasksResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MixOperateTasksResponse")
    public TaskOperationResult mixOperateTasks(
            @WebParam(name = "tasks", targetNamespace = "http://tempuri.org/")
                    ArrayOfTaskOperationMessage tasks);

    /**
     * 
     * @param tasks
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MixOperateTasksOfJson", action = "http://tempuri.org/IMessageCenterService/MixOperateTasksOfJson")
    @WebResult(name = "MixOperateTasksOfJsonResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MixOperateTasksOfJson", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MixOperateTasksOfJson")
    @ResponseWrapper(localName = "MixOperateTasksOfJsonResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MixOperateTasksOfJsonResponse")
    public String mixOperateTasksOfJson(
            @WebParam(name = "tasks", targetNamespace = "http://tempuri.org/")
                    String tasks);

    /**
     * 
     * @param atasksJsonValue
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InsertAccomplishedTasks", action = "http://tempuri.org/IMessageCenterService/InsertAccomplishedTasks")
    @WebResult(name = "InsertAccomplishedTasksResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InsertAccomplishedTasks", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertAccomplishedTasks")
    @ResponseWrapper(localName = "InsertAccomplishedTasksResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertAccomplishedTasksResponse")
    public String insertAccomplishedTasks(
            @WebParam(name = "atasksJsonValue", targetNamespace = "http://tempuri.org/")
                    String atasksJsonValue);

}
